# Generated by Django 3.1.1 on 2020-09-08 18:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='posicion',
            field=models.IntegerField(default=0, verbose_name='Posicion'),
        ),
        migrations.AlterField(
            model_name='page',
            name='contenido',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(max_length=200, unique=True, verbose_name='URL amigable'),
        ),
    ]
