# Generated by Django 3.1.1 on 2020-09-08 18:44

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('contenido', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('imagen', models.ImageField(default='null', upload_to='', verbose_name='Imagen')),
                ('publico', models.BooleanField(verbose_name='Publicado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('categorias', models.ManyToManyField(blank=True, null=True, to='blogapp.Categoria', verbose_name='Categorías')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
        ),
    ]
